### ISSUE TITLE
Does this repository have a license?

### ISSUE THREAD

**Issue by jfy133** [cordeliadillon/bingo#17]
Hello,

I was looking for a customised/self hosted bingo app  for a little bit of fun for an event I'm helping to organise, and stumbled across this repository.

After playing around in a fork, it works very nicely (and was very easy to set up - thanks for the clear documentation!). 

Before i actually use it for the event though, I would like to ask if you're happy with me making and using the fork itself - and if there is any particular license/attribution you would want associated with the code at all? I don't see any license files in the repo currently.

If you're not comfortable with the code being used by others, I'm happy to delete my repository and find another solution.

Cheers,
James

**Comment by cordeliadillon** [comment]
Hi James,

Sorry for the late reply - I just added an MIT license. Feel free to use for future events!

Cheers,
Cordelia

**Comment by jfy133** [comment]
Awesome, thank you!
